"""empty message

Revision ID: 64199e2c4513
Revises: 5eed70a8121
Create Date: 2016-04-08 13:43:26.184105

"""

# revision identifiers, used by Alembic.
revision = '64199e2c4513'
down_revision = '5eed70a8121'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    ### end Alembic commands ###
